<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;

class ApiController extends Controller
{
    protected $paginate = 1;

    public function __construct()
    {
        $this->middleware('auth:sanctum');
    }

    public function callAction($method, $parameters)
    {

        if (get_class($this) == 'App\Http\Controllers\Api\ProjectController' && $method == 'index') {
            Gate::authorize('employee');
        }else {
            Gate::authorize($method);
        }

        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }
}
