<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Gate;

class ApiController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:sanctum');
    }

    public function callAction($method, $parameters)
    {
        Gate::authorize($method);

        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }
}
