<?php

namespace App\Http\Controllers\Api;

use App\Http\Requests\DepartmentRequest;
use App\Models\Department;
use App\Traits\ApiResponser;
use Illuminate\Http\Request;
use Illuminate\Pagination\Paginator;
use Illuminate\Support\Facades\Gate;

class DepartmentController extends ApiController
{
    use ApiResponser;

    public function callAction($method, $parameters)
    {
        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        $departments = Department::paginate(request()->all());

        return $this->success($departments, 200);
    }

    public function list()
    {
        $departments = Department::get();
        $departments = collect($departments)->pluck('name', 'id');

        return $this->success($departments, 200);
    }

    public function show($id)
    {
        $department = Department::find($id);
        if (empty($department)) {
            return $this->error('Department not exists.', 403);
        }
        return $this->success(['department' => $department, 'users' => $department->users]);
    }

    public function store(DepartmentRequest $request)
    {
        $attr = $request->validated();

        $attr['created_by_user_id'] = auth()->user()->id;

        Department::create($attr);

        return $this->success([], 'Department created.', 201);
    }

    public function update($id, DepartmentRequest $request)
    {
        $attr = $request->validated();

        $department = Department::where('id' , '=', $id)->update($attr);

        return $this->success($department, 'Department updated.', 200);
    }
}
