<?php

namespace App\Http\Controllers\Api;

use App\Models\User;
use App\Traits\ApiResponser;

class EmployeeController extends ApiController
{
    use ApiResponser;

    public function callAction($method, $parameters)
    {
        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        $employees = User::where('manage_id', '=', null)->paginate(request()->all());

        return $this->success($employees, 200);
    }

    public function list()
    {
        $employees = User::where('manage_id', '=', null)->get();
        $employees = collect($employees)->pluck('email', 'id');

        return $this->success($employees, 200);
    }
}
