<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Department extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'description',
        'access_code',
        'created_by_user_id'
    ];

    public function save(array $options = [])
    {
        $this->attributes['access_code'] = 'EMP_' . Str::uuid()->toString();

        return parent::save($options); // TODO: Change the autogenerated stub
    }

    public function users()
    {
        return $this->hasMany(User::class);
    }
}
